# import win32com.client

# mailads = []

# outlook_read = win32com.client.Dispatch("Outlook.Application")
# mapi = outlook_read.GetNamespace("MAPI")

# inbox = mapi.GetDefaultFolder(6).Folders.Item("Promotionsdokureihe")
# msgs = inbox.Items

# for msg in msgs:
#     if msg.Class==43:
#            if msg.SenderEmailType=='EX':
#                mailads.append(msg.Sender.GetExchangeUser().PrimarySmtpAddress)
#            else:
#                mailads.append(msg.SenderEmailAddress)
# mailads.reverse()

# mailitem = 0x0
# newmail = outlook_read.CreateItem(mailitem)
# newmail.Subject = "PhD Video Campaign - First Video Dates"
# newmail.To = "leah.bohr@zv.uni-freiburg.de" 
# newmail.CC = "eva.rueskamp@zv.uni-freiburg.de"
# newmail.BCC = "; ".join(mailads)
# newmail.Body = "***GERMAN VERSION BELOW*** \nDear PhD candidates, \n\nThank you for your interest in our video campaign, we were delighted to see this many sign-ups! \n\nWe’re releasing the first filming dates today. The meetings will start in late February, please see the Doodle below for specific dates and times: \n\nhttps://doodle.com/meeting/participate/id/e16Q8EZa \n\nEach slot is limited to 45 minutes, which should give you enough time to get comfortable in front of the camera. If you’ve signed up for a slot and find that you cannot attend for whatever reason, please let us know as early as possible! \n\nWe kindly ask you to come to the filming locations prepared – you should have a rough idea of what you want to say. As a reminder, these are the 3 questions we will ask you:\n\n1. What do you research? (Explain it to someone who is not an expert on your topic, perhaps your grandparents!) \n2.Why does this research matter? \n3.Why did you choose Freiburg? \n\nWe will be releasing more dates once this doodle is full. If none of the dates or times work for you, you can reach out and we can find an individual date. Once you have signed up, we will get in touch to decide on a filming location, ideally a space you are comfortable in. Good examples would be your lab, your office or other project-related locations. \n\nShould you have any questions or concerns, don’t hesitate to reach out! \n\nBest wishes,\nLeah Bohr\n\n\n*****************************************\nLiebe Doktorand*innen,\n\nDanke für Ihr zahlreiches Interesse an unserer Videokampagne, wir haben uns sehr über Ihre Anmeldungen gefreut! \n\nWir schicken Ihnen anbei die ersten Termine für die Videodrehs. Es geht gegen Ende Februar los; die genauen Daten und Zeiten finden Sie hier im Doodle: \n\nhttps://doodle.com/meeting/participate/id/e16Q8EZa \n\nJeder Zeitslot ist auf 45 Minuten angelegt, was Ihnen genug Zeit geben sollte, um sich in der Interviewsituation wohlzufühlen. Sollten Sie einen Termin absagen müssen, tun Sie dies bitte rechtzeitig im Voraus. \n\nWir bitten Sie außerdem, vorbereitet zum Videodreh zu kommen – sprich, überlegen Sie sich vorher grob, was Sie sagen möchten. Wir werden Sie mit den folgenden 3 Fragen konfrontieren: \n\n1. Was forschen Sie? (Erklären Sie es in möglichst einfachen Worten.) \n2. Warum ist Ihre Forschung relevant? \n3. Warum haben Sie sich für Freiburg entschieden? \n\nSobald dieses Doodle voll ist, schicken wir einen weiteren Doodle mit Terminen aus. Sollten Sie an keinem der angebotenen Termine Zeit haben, kontaktieren Sie uns gerne und wir finden gemeinsam einen individuellen Termin. Sobald Sie sich für einen Termin eingetragen haben, melden wir uns, um gemeinsam eine Location zu finden. Idealerweise wäre diese Location bei Ihnen im Lab, im Büro oder an einem anderen Ort, der zu Ihrer Forschung passt. \n\nBei Fragen oder sonstigen Anliegen können Sie sich gerne jederzeit melden! \n\nBeste Grüße, \nLeah Bohr"

# newmail.Display()


# mylist1 = ["The election results are great.", "The election results are pretty good.", "The election results are okay.", "The election results are not that good.", "The election results are terrible.", "The city's climate policies are great.", "The city's climate policies are pretty good.", "The city's climate policies are okay.", "The city's climate policies are not that good.", "The city's climate policies are terrible.", "The mayor's decision about the housing crisis is great.", "The mayor's decision about the housing crisis is pretty good.", "The mayor's decision about the housing crisis is okay.", "The mayor's decision about the housing crisis is not that good.", "The mayor's decision about the housing crisis is terrible.", "The jurisdiction in our district is great.", "The jurisdiction in our district is pretty good.", "The jurisdiction in our district is okay.", "The jurisdiction in our district is not that good.", "The jurisdiction in our district is terrible.", "Our public transport system is great.", "Our public transport system is pretty good.", "Our public transport system is okay.", "Our public transport system is not that good.", "Our public transport system is terrible.", "The way our country counteracts school shootings is great.", "The way our country counteracts school shootings is pretty good.", "The way our country counteracts school shootings is okay.", "The way our country counteracts school shootings is not that good.", "The way our country counteracts school shootings is terrible.", "Women's access to reproductive rights is great.", "Women's access to reproductive rights is pretty good.", "Women's access to reproductive rights is okay.", "Women's access to reproductive rights is not that good.", "Women's access to reproductive rights is terrible.", "The way the farmers treat their animals is great.", "The way the farmers treat their animals is pretty good.", "The way the farmers treat their animals is okay.", "The way the farmers treat their animals is not that good.", "The way the farmers treat their animals is terrible.", "Free speech policies on Twitter are great.", "Free speech policies on Twitter are pretty good.", "Free speech policies on Twitter are okay.", "Free speech policies on Twitter are not that good.", "Free speech policies on Twitter are terrible.", "Our immigration laws are great.", "Our immigration laws are pretty good.", "Our immigration laws are okay.", "Our immigration laws are not that good.", "Our immigration laws are terrible."]

# mylist2 = ["The election results are amazing.", "The election results are decent.", "The election results are interesting.", "The election results are rather bad.", "The election results are awful.", "The city's climate policies are amazing.", "The city's climate policies are decent.", "The city's climate policies are interesting.", "The city's climate policies are rather bad.", "The city's climate policies are awful.", "The mayor's decision about the housing crisis is amazing.", "The mayor's decision about the housing crisis is decent.", "The mayor's decision about the housing crisis is interesting.", "The mayor's decision about the housing crisis is rather bad.", "The mayor's decision about the housing crisis is awful.", "The jurisdiction in our district is amazing.", "The jurisdiction in our district is decent.", "The jurisdiction in our district is interesting.", "The jurisdiction in our district is rather bad.", "The jurisdiction in our district is awful.", "Our public transport system is amazing.", "Our public transport system is decent.", "Our public transport system is interesting.", "Our public transport system is rather bad.", "Our public transport system is awful.", "The way our country counteracts school shootings is amazing.", "The way our country counteracts school shootings is decent.", "The way our country counteracts school shootings is interesting.", "The way our country counteracts school shootings is rather bad.", "The way our country counteracts school shootings is awful.", "Women's access to reproductive rights is amazing.", "Women's access to reproductive rights is decent.", "Women's access to reproductive rights is interesting.", "Women's access to reproductive rights is rather bad.", "Women's access to reproductive rights is awful.", "The way the farmers treat their animals is amazing.", "The way the farmers treat their animals is decent.", "The way the farmers treat their animals is interesting.", "The way the farmers treat their animals is rather bad.", "The way the farmers treat their animals is awful.", "Free speech policies on Twitter are amazing.", "Free speech policies on Twitter are decent.", "Free speech policies on Twitter are interesting.", "Free speech policies on Twitter are rather bad.", "Free speech policies on Twitter are awful.", "Our immigration laws are amazing.", "Our immigration laws are decent.", "Our immigration laws are interesting.", "Our immigration laws are rather bad.", "Our immigration laws are awful."]

# tuple_list = []

# for i in range(len(mylist1)):
#     element = [mylist1[i], mylist2[i]]
#     tuple_list.append(element)
    
# print(tuple_list)

x = ['The election results are great.', 'The election results are pretty good.', 'The election results are okay.', 'The election results are poor.', 'The election results are terrible.', "The city's climate policies are great.", "The city's climate policies are pretty good.", "The city's climate policies are okay.", "The city's climate policies are poor.", "The city's climate policies are terrible.", "The mayor's decision about the housing crisis is great.", "The mayor's decision about the housing crisis is pretty good.", "The mayor's decision about the housing crisis is okay.", "The mayor's decision about the housing crisis is poor.", "The mayor's decision about the housing crisis is terrible.", 'The jurisdiction in our district is great.', 'The jurisdiction in our district is pretty good.', 'The jurisdiction in our district is okay.', 'The jurisdiction in our district is poor.', 'The jurisdiction in our district is terrible.', 'Our public transport system is great.', 'Our public transport system is pretty good.', 'Our public transport system is okay.', 'Our public transport system is poor.', 'Our public transport system is terrible.', 'The way our country counteracts school shootings is great.', 'The way our country counteracts school shootings is pretty good.', 'The way our country counteracts school shootings is okay.', 'The way our country counteracts school shootings is poor.', 'The way our country counteracts school shootings is terrible.', "Women's access to reproductive rights is great.", "Women's access to reproductive rights is pretty good.", "Women's access to reproductive rights is okay.", "Women's access to reproductive rights is poor.", "Women's access to reproductive rights is terrible.", 'The way the farmers treat their animals is great.', 'The way the farmers treat their animals is pretty good.', 'The way the farmers treat their animals is okay.', 'The way the farmers treat their animals is poor.', 'The way the farmers treat their animals is terrible.', 'Free speech policies on Twitter are great.', 'Free speech policies on Twitter are pretty good.', 'Free speech policies on Twitter are okay.', 'Free speech policies on Twitter are poor.', 'Free speech policies on Twitter are terrible.', 'Our immigration laws are great.', 'Our immigration laws are pretty good.', 'Our immigration laws are okay.', 'Our immigration laws are poor.', 'Our immigration laws are terrible.']

print(len(x))